### PR TITLE
WIP: Cleanup import paths

### PR DESCRIPTION
**Pull request by abemac**
See https://github.com/Asymmetrik/ngx-starter/issues/38

### CODE REVIEW

**Comment by abemac** [comment]
Is everyone okay with the import path aliases I made in tsconfig.json? I want to check before I update all the files

**Review by brianghig — APPROVED** [review]

**Comment by reblace** [comment]
I thought we'd previously decided to avoid using aliased paths. My concern is that this means you have to know where to look to find the actual path to the imports. And, you have to recognize the difference between an actual NPM module and an aliased path ('@core' looks like an NPM module namespace). IMO, it hurts the readability of the code.

**Comment by jrassa** [comment]
@reblace Sorry I didn't remember the previous discussion.  @abemac suggested and it seemed like a good idea.  To be clear, this wouldn't change every import statement.  The aliases would only be used when importing across the 3 primary sections (site, core and common).  So, for example, within site, we would still use relative imports for anything else in site, but would use an alias when importing something from core or common.

Would it be better/clearer if we changed the aliases?  Looking around online, I saw several suggestions to use `@app` to indicate it is importing from within the application.   Or we could use `@ngx-starter` to be really explicit.

**Comment by abemac** [comment]
We could create the aliases without the "@". I kind of like having an alias for app, assets, and styles. The imports would look like 
```
import {Something} from 'app/core/something'
```
or 
```
import {Something} from 'app/common/something'
```

This wouldn't conflict with relative imports because relative would start with `./`

**Pull request closed without merging**
