### PR TITLE
migrating help feature

### PR DESCRIPTION
**Pull request by jrassa**
Bringing over help feature from existing app, updated for ng7.  Also include breadcrumb component.

### CODE REVIEW

**Comment by brianghig** [comment]
@jrassa functionality looks good! Thanks for bringing this over. Are there any SCSS files for the breadcrumbs that we can add? At the moment, it looks like it may be in need of padding, text decoration, and hover indicators.

screen shot 2018-11-05 at 2 06 27 pm

**Comment by jrassa** [comment]
@brianghig styling has been updated.  One question I had is that I wasn't sure if help should go under common or core.  I went with common so that it could be excluded more easily if an app didn't want/need it, but I would be fine with either.

**Comment by reblace** [comment]
Probably core. Core is for things that are a part of the site or are only
expected to be created once per site. Common is for reusable utilities that
are used by a lot of components.

**Comment by brianghig** [comment]
Code inspection looks good, but I haven't executed the latest linting and tests on this branch.

**Pull request merged**
