### PR TITLE
tslint update

### PR DESCRIPTION
**Pull request by jrassa**
Looking at leveraging tslint more.  I updated the rules to more closely match those generated by ng cli when creating a new project (which match up with the Angular style guide).  This includes additional Angular specific rules from codelyzer.  Rule changes are up for discussion if anyone feels strongly for/against any of the changes.

For now, I changed any rules that were generating errors to generate warnings.  That way downstream projects won't be forced to fix a bunch of lint errors immediately.

### CODE REVIEW

**Comment by brianghig** [comment]
@jrassa thanks for bringing us closer to tslint standards! IMO, we should leave most / all of these as errors unless they're causing functional issues. Having clean, consistent coding guidelines seems to help the transition between projects. Otherwise, are we left with a bunch of warning logs that folks would tend to ignore over time?

**Comment by jrassa** [comment]
@brianghig I agree that we should set them as errors.  I was mainly considering having a short transition period of maybe a couple of weeks at most before we switch to errors.  That would allow us time to make changes to our upstream projects without being forced to fix everything immediately.  I am happy to enable them now though.

**Comment by brianghig** [comment]
@jrassa whew! Lots of changes! Thanks for tackling this, especially with the "rip the bandaid" approach.

**Comment by jrassa** [comment]
I fixed most of the warnings and switched them to be errors.  Many can be autofixed using `ng lint --fix`.  I left a few as warnings as fixing them will be a bit more invasive (renaming things).  I will prepare a follow up PR to handle those changes.

**Comment by brianghig** [comment]
Makes sense. There's one error that's preventing me from building / starting the app at the moment:

```
ERROR in src/app/core/admin/end-user-agreement/admin-edit-eua.component.ts(13,14): error TS2420: Class 'AdminUpdateEuaComponent' incorrectly implements interface 'OnDestroy'.
  Property 'ngOnDestroy' is missing in type 'AdminUpdateEuaComponent' but required in type 'OnDestroy'.
```

**Comment by brianghig** [comment]
Pending a TravisCI successful completion, I'm good with this update. Ran it locally to verify, and all seemed fine.

**Review by brianghig — APPROVED** [review]

**Pull request merged**
