### PR TITLE
:arrow_up: Upgrading Dependencies

### PR DESCRIPTION
**Pull request by ltherrien**
### Minor
* `jquery` - `3.4.1` to `3.5.1`
* `lodash` - locked `4.17`
* `moment` - `2.22` to `2.29.1`
* `popper` - locked `1.16`
* `rxjs` - `6.5.4` to `6.6.3`
* `zone.js` - `0.10.2` to `0.11.3`

### Major
* `@angular`
* `@ng-select/ng-select`
* `@ngneat/until-destroy`
* `core-js`
* `socket.io-client`
* `tslib`

## Weird
* `bootstrap`

### Minor
* `@types/jasmine` - `3.5.0` to `3.6.2`
* `@types/jasminewd2` - locked `2.0`
* `@types/lodash` - locked `4.14`
* `@types/socket.io-client` - locked `1.4`
* `@types/webpack` - locked `4.41`
* `husky` - `4.2.1` to `4.3.0`
* `jasmine-core` - `3.5.0` to `3.6.0`
* `karma-chrome-launcher` - locked `3.1`
* `karma-jasmine-html-reporter` - `1.4.2` to `1.5.4`
* `lint-staged` - `10.0.7` to `10.5.2`
* `stylelint` - `13.0.0.` to `13.8.0`
* `stylelint-config-prettier` - locked `8.0`
* `stylelint-config-recommended-scss` - locked `4.2`
* `stylelint-prettier` - locked `1.1`
* `stylelint-scss` - `3.14.2` to `3.18.0`
* `tslint` - `6.1.0` to `6.1.3`
* `tslint-config-prettier` - locked `1.18`
* `tslint-plugin-prettier` - locked `2.3`

### Major
* `@angular`
* `codelyzer`
* `jasmine-spec-reporter`
* `karma`
* `karma-coverage-istanbul-reporter`
* `karma-jasmine`
* `karma-junit-reporter`
* `nodemon`
* `prettier`
* `protractor`
* `ts-node`
* `typescript`
* `webpack-bundle-analyzer`

### CODE REVIEW

**Comment by ltherrien** [comment]
Just a note; I only updated minor versions!

**Comment by brianghig** [comment]
@ltherrien @jrassa @tzfx we'll have to pay close attention to the zone.js upgrade from 0.10 to 0.11 due to https://github.com/angular/angular/blob/master/packages/zone.js/CHANGELOG.md#breaking-changes-since-zonejs-v0111

**Comment by ltherrien** [comment]
> @ltherrien @jrassa @tzfx we'll have to pay close attention to the zone.js upgrade from 0.10 to 0.11 due to https://github.com/angular/angular/blob/master/packages/zone.js/CHANGELOG.md#breaking-changes-since-zonejs-v0111

Thank you for mentioning that! I had taken a quick look at the code to make sure not much was different with that change; lemme double check and report back.

**Comment by ltherrien** [comment]
I believe we'll be okay to upgrade because `src/polyfills.ts` contains the following code `import 'zone.js/dist/zone` as recommended in the blog post you mentioned.

Everyone should definitely double check that they're not just `import zone.js` in their code, though.

**Review by jrassa — APPROVED** [review]
Tested in starter and downstream.  Everything looked good to me.

**Review by brianghig — APPROVED** [review]

**Pull request merged**
